name: swipe_transfer_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  url_launcher: ^6.0.20
  # 状態管理
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1

  # ルーティング
  go_router: ^14.8.1

  # DB
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # DB（コード生成用）
  isar_generator: ^3.1.0
  build_runner: ^2.4.6 

flutter:
  assets:
    - assets/images/

  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true # iOSでは透明部分を削除